# Generated by Django 2.2.1 on 2019-05-30 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190530_2300'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
