# Generated by Django 2.2.1 on 2019-06-05 16:02

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20190603_1035'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='info',
            options={'verbose_name': 'Додаткова інформація'},
        ),
        migrations.AlterField(
            model_name='info',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Номер телефону'),
        ),
    ]
