# Generated by Django 2.2.1 on 2019-06-04 23:35

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car', models.CharField(default='Автомобіль', max_length=100)),
                ('problem', models.TextField()),
                ('date_begin', models.DateField(default=datetime.date.today)),
                ('state', models.CharField(choices=[('Не підтверджено', 'Не підтверджено'), ('Підтверджено', 'Підтверджено'), ('Виконується', 'Виконується'), ('Виконано', 'Виконано')], default='Не підтверджено', max_length=20)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
