# Generated by Django 2.2.1 on 2019-06-04 23:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='date_end',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
