# Generated by Django 2.2.1 on 2019-06-05 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0004_request_urgently'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Name', max_length=50, verbose_name='Назва послуги')),
                ('price', models.CharField(default='0 грн', max_length=50, verbose_name='Ціна послуги')),
            ],
        ),
    ]
