# Generated by Django 2.2.1 on 2019-06-05 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0010_auto_20190605_1521'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='request',
            options={'verbose_name': 'Замовлення'},
        ),
        migrations.AlterModelOptions(
            name='services',
            options={'verbose_name': 'Послуги'},
        ),
    ]
