# Generated by Django 2.2.1 on 2019-06-05 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0011_auto_20190605_1551'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='request',
            options={'verbose_name_plural': 'Замовлення'},
        ),
        migrations.AlterModelOptions(
            name='services',
            options={'verbose_name_plural': 'Послуги'},
        ),
    ]
