# Generated by Django 2.2.1 on 2019-06-05 16:02

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0012_auto_20190605_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Користувач'),
        ),
        migrations.AlterField(
            model_name='request',
            name='date_begin',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата початку робити'),
        ),
        migrations.AlterField(
            model_name='request',
            name='date_end',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата закінчення робити'),
        ),
        migrations.AlterField(
            model_name='request',
            name='state',
            field=models.CharField(choices=[('Не підтверджено', 'Не підтверджено'), ('Підтверджено', 'Підтверджено'), ('Виконується', 'Виконується'), ('Виконано', 'Виконано')], default='Не підтверджено', max_length=20, verbose_name='Стан'),
        ),
    ]
