# Generated by Django 2.2.1 on 2019-06-07 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0014_auto_20190605_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='state',
            field=models.CharField(choices=[('Не підтверджено', 'Не підтверджено'), ('Підтверджено', 'Підтверджено'), ('Виконується', 'Виконується'), ('Виконано', 'Виконано'), ('Оплачено', 'Оплачено')], default='Не підтверджено', max_length=20, verbose_name='Стан'),
        ),
    ]
