# Generated by Django 2.2.1 on 2019-06-07 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0015_auto_20190607_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Ціна послуги(грн)'),
        ),
    ]
