# Generated by Django 2.2.1 on 2019-06-09 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0018_auto_20190608_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='add_info',
            field=models.TextField(blank=True, default='', verbose_name='Додаткова інформація'),
        ),
    ]
